
["Ender Guardian"]
	#EnderGuardian's Damage.
	#Range: 0.0 ~ 1000000.0
	EnderGuardianDamage = 16.0
	#EnderGuardianBlockBreaking radius
	#Range: 0 ~ 20
	"EnderGuardianBlockBreaking X" = 15
	#ruined citadel spawn
	RuinedcitadelSpawn = true
	#Guardian's Immune to Long distance attack range.
	#Range: 1.0 ~ 1000000.0
	"Guardian's prevent attacks from far away Range" = 12.0
	#EnderGuardian's DamageCap
	#Range: 0 ~ 1000000
	EnderGuardianDamageCap = 22
	#Ender guardian's block breaking ignore the MobGriefing
	EnderguardianBlockBreaking = true
	#EnderGuardian's Health
	#Range: 0.0 ~ 1000000.0
	EnderGuardianHealth = 300.0
	#EnderGuardianBlockBreaking radius
	#Range: 0 ~ 10
	"EnderGuardianBlockBreaking Y" = 2
	#EnderGuardianBlockBreaking radius
	#Range: 0 ~ 20
	"EnderGuardianBlockBreaking Z" = 15

["Netherite Monstrosity"]
	#soul black smith spawn
	SoulblacksmithSpawn = true
	#Monstrosity's bodyBlocking verdict
	NetheritemonstrosityBodyBloking = true
	#Monstrosity's Damage
	#Range: 0.0 ~ 1000000.0
	MonstrosityDamage = 22.0
	#Monstrosity's DamageCap
	#Range: 0 ~ 1000000
	MonstrosityDamageCap = 22
	#Monstrosity's Health
	#Range: 0.0 ~ 1000000.0
	MonstrosityHealth = 360.0
	#Monstrosity's Lavabomb amount
	#Range: 1 ~ 1000000
	Lavabombamount = 3
	#Monstrosity's Lavabomb magazine.
	#Range: 1 ~ 1000000
	LavabombMagazine = 3
	#Monstrosity's Immune to Long distance attack range.
	#Range: 1.0 ~ 1000000.0
	"Monstrosity's prevent attacks from far away Range" = 18.0

["Ender Golem"]
	#Golem's Health
	#Range: 0.0 ~ 1000000.0
	GolemHealth = 150.0
	#Ender Golem's block breaking ignore the MobGriefing
	EndergolemBlockBreaking = false
	#Endergolem's Immune to Long distance attack range.
	#Range: 1.0 ~ 1000000.0
	"Endergolem's prevent attacks from far away Range" = 6.0
	#Golem's Damage.
	#Range: 0.0 ~ 1000000.0
	GolemDamage = 10.0

[Etc]
	#BossMusic(on/off)
	"BossMusic(on/off)" = true
	#Lava bomb's Radius
	#Range: 1 ~ 7
	Lavabombradius = 2
	#ScreenShake(on/off)
	"ScreenShake(on/off)" = true
	#Void Rune's Damage
	#Range: 0 ~ 1000000
	Voidrunedamage = 7

[Ignis]
	#Ignis's DamageCap
	#Range: 0 ~ 1000000
	IgnisDamageCap = 20
	#Ignis's Health
	#Range: 0.0 ~ 1000000.0
	IgnisHealth = 333.0
	#Ignis's Immune to Long distance attack range.
	#Range: 1.0 ~ 1000000.0
	"Ignis's prevent attacks from far away Range" = 20.0
	#Ignis's Damage.
	#Range: 0.0 ~ 1000000.0
	IgnisDamage = 14.0

