#Draw a black box behind effect icons
effect_box = true
#A list of effects that should not be registered nor shown on JEI
hidden_effects = ["mutantmore:chemicalated","tconstruct:bleeding","tconstruct:calcified","tconstruct:carry","tconstruct:fireball_cooldown","tconstruct:insatiable","tconstruct:momentum","tconstruct:teleport_cooldown"]

